<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Product;
use App\Models\Category;

class ProductSeeder extends Seeder
{
    public function run(): void
    {
        $categories = Category::all();
        
        // Product data with images
        $products = [
            // Beds
            [
                'name' => 'Shreejee Blessings Wood Daffodil King Bed with Box Storage (Walnut)',
                'price' => 21990,
                'original_price' => 69000,
                'category' => 'beds',
                'subcategory' => 'King Size Beds',
                'image' => 'https://images.unsplash.com/photo-1631049307264-da0ec9d70304?w=800',
                'rating' => 4.5,
                'reviews' => 24,
                'in_stock' => true,
                'is_featured' => true,
                'hot_offer' => true,
                'offer_percentage' => 68,
                'description' => 'Premium king size bed with spacious box storage. Made from high-quality walnut wood with elegant design.',
            ],
            [
                'name' => 'Shreejee Blessings Wood King Bed without Storage (Walnut)',
                'price' => 15500,
                'original_price' => 50000,
                'category' => 'beds',
                'subcategory' => 'King Size Beds',
                'image' => 'https://images.unsplash.com/photo-1586023492125-27b2c045efd7?w=800',
                'rating' => 4.3,
                'reviews' => 18,
                'in_stock' => true,
                'is_featured' => true,
                'hot_offer' => true,
                'offer_percentage' => 69,
                'description' => 'Elegant king size bed without storage. Perfect for modern bedrooms.',
            ],
            [
                'name' => 'Shreejee Blessings Wood Queen Bed with Storage (Oak)',
                'price' => 18990,
                'original_price' => 45000,
                'category' => 'beds',
                'subcategory' => 'Queen Size Beds',
                'image' => 'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=800',
                'rating' => 4.6,
                'reviews' => 32,
                'in_stock' => true,
                'is_featured' => false,
                'hot_offer' => true,
                'offer_percentage' => 58,
                'description' => 'Spacious queen bed with under-bed storage compartments.',
            ],
            [
                'name' => 'Modern Platform Bed (Teak Wood)',
                'price' => 24990,
                'original_price' => 55000,
                'category' => 'beds',
                'subcategory' => 'Platform Beds',
                'image' => 'https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?w=800',
                'rating' => 4.7,
                'reviews' => 45,
                'in_stock' => true,
                'is_featured' => true,
                'hot_offer' => false,
                'offer_percentage' => null,
                'description' => 'Contemporary platform bed in premium teak wood finish.',
            ],
            [
                'name' => 'Hydraulic Storage Bed (Mahogany)',
                'price' => 32990,
                'original_price' => 75000,
                'category' => 'beds',
                'subcategory' => 'Hydraulic Beds',
                'image' => 'https://images.unsplash.com/photo-1631889993954-1b3b9b4b5e5e?w=800',
                'rating' => 4.8,
                'reviews' => 56,
                'in_stock' => true,
                'is_featured' => true,
                'hot_offer' => true,
                'offer_percentage' => 56,
                'description' => 'Luxury hydraulic bed with easy-lift storage mechanism.',
            ],
            [
                'name' => 'Classic Wooden Bed with Headboard (Sheesham)',
                'price' => 17990,
                'original_price' => 42000,
                'category' => 'beds',
                'subcategory' => 'Queen Size Beds',
                'image' => 'https://images.unsplash.com/photo-1631049307264-da0ec9d70304?w=800',
                'rating' => 4.4,
                'reviews' => 28,
                'in_stock' => true,
                'is_featured' => false,
                'hot_offer' => true,
                'offer_percentage' => 57,
                'description' => 'Beautiful classic wooden bed with elegant headboard in premium sheesham wood.',
            ],
            
            // Sofa Sets
            [
                'name' => 'Duroflex Ease 3 Seater Fabric Sofa In Beige Colour',
                'price' => 19152,
                'original_price' => 33600,
                'category' => 'sofa-sets',
                'subcategory' => '3-Seaters Sofas',
                'image' => 'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=800',
                'rating' => 4.4,
                'reviews' => 28,
                'in_stock' => true,
                'is_featured' => true,
                'hot_offer' => true,
                'offer_percentage' => 43,
                'description' => 'Comfortable 3-seater fabric sofa in elegant beige color.',
            ],
            [
                'name' => 'Home Lifestylez Belfast 3 Seater Velvet Sofa In Grey Color',
                'price' => 40500,
                'original_price' => 55500,
                'category' => 'sofa-sets',
                'subcategory' => '3-Seaters Sofas',
                'image' => 'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=800',
                'rating' => 4.6,
                'reviews' => 41,
                'in_stock' => true,
                'is_featured' => true,
                'hot_offer' => false,
                'offer_percentage' => null,
                'description' => 'Luxurious velvet sofa in modern grey shade.',
            ],
            [
                'name' => 'Caraven 2 Seater Velvet Sofa In Navy Blue Color',
                'price' => 27500,
                'original_price' => 40500,
                'category' => 'sofa-sets',
                'subcategory' => '2-Seater Sofas',
                'image' => 'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=800',
                'rating' => 4.5,
                'reviews' => 35,
                'in_stock' => true,
                'is_featured' => false,
                'hot_offer' => true,
                'offer_percentage' => 32,
                'description' => 'Compact 2-seater velvet sofa perfect for small spaces.',
            ],
            [
                'name' => 'Duroflex Utopia 1 Seater Fabric Sofa In Grey Colour',
                'price' => 12500,
                'original_price' => 22000,
                'category' => 'sofa-sets',
                'subcategory' => '1-Seater Sofas',
                'image' => 'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=800',
                'rating' => 4.2,
                'reviews' => 19,
                'in_stock' => true,
                'is_featured' => false,
                'hot_offer' => true,
                'offer_percentage' => 43,
                'description' => 'Stylish single seater fabric sofa in grey.',
            ],
            [
                'name' => 'Premium Leather 3 Seater Sofa Set',
                'price' => 89900,
                'original_price' => 150000,
                'category' => 'sofa-sets',
                'subcategory' => '3-Seaters Sofas',
                'image' => 'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=800',
                'rating' => 4.9,
                'reviews' => 67,
                'in_stock' => true,
                'is_featured' => true,
                'hot_offer' => true,
                'offer_percentage' => 40,
                'description' => 'Luxury genuine leather 3-seater sofa set with premium finish.',
            ],
            [
                'name' => 'Modern L-Shaped Corner Sofa Set (Grey Fabric)',
                'price' => 45900,
                'original_price' => 85000,
                'category' => 'sofa-sets',
                'subcategory' => 'L-Shaped Sofas',
                'image' => 'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=800',
                'rating' => 4.6,
                'reviews' => 42,
                'in_stock' => true,
                'is_featured' => true,
                'hot_offer' => true,
                'offer_percentage' => 46,
                'description' => 'Spacious L-shaped corner sofa perfect for modern living rooms. Comfortable and stylish.',
            ],
            
            // Dining Tables
            [
                'name' => 'Modern 6 Seater Dining Table Set (Oak Wood)',
                'price' => 45900,
                'original_price' => 85000,
                'category' => 'dining-table-sets',
                'subcategory' => '6-Seater Dining Table',
                'image' => 'https://images.unsplash.com/photo-1586023492125-27b2c045efd7?w=800',
                'rating' => 4.7,
                'reviews' => 52,
                'in_stock' => true,
                'is_featured' => true,
                'hot_offer' => true,
                'offer_percentage' => 46,
                'description' => 'Elegant 6-seater dining table with matching chairs in oak finish.',
            ],
            [
                'name' => 'Classic 4 Seater Dining Table (Teak)',
                'price' => 32900,
                'original_price' => 65000,
                'category' => 'dining-table-sets',
                'subcategory' => '4-Seater Dining Table',
                'image' => 'https://images.unsplash.com/photo-1586023492125-27b2c045efd7?w=800',
                'rating' => 4.5,
                'reviews' => 38,
                'in_stock' => true,
                'is_featured' => false,
                'hot_offer' => true,
                'offer_percentage' => 49,
                'description' => 'Beautiful 4-seater dining table in premium teak wood.',
            ],
            
            // TV Units
            [
                'name' => 'Wall Mount TV Unit with Storage (Walnut)',
                'price' => 28900,
                'original_price' => 55000,
                'category' => 'tv-units',
                'subcategory' => 'Wall Mount Tv Units',
                'image' => 'https://images.unsplash.com/photo-1586023492125-27b2c045efd7?w=800',
                'rating' => 4.6,
                'reviews' => 43,
                'in_stock' => true,
                'is_featured' => true,
                'hot_offer' => true,
                'offer_percentage' => 47,
                'description' => 'Modern wall-mounted TV unit with ample storage space.',
            ],
            [
                'name' => 'Modular TV Cabinet with Hutch',
                'price' => 35900,
                'original_price' => 70000,
                'category' => 'tv-units',
                'subcategory' => 'Hutch Tv Units',
                'image' => 'https://images.unsplash.com/photo-1586023492125-27b2c045efd7?w=800',
                'rating' => 4.8,
                'reviews' => 61,
                'in_stock' => true,
                'is_featured' => true,
                'hot_offer' => false,
                'offer_percentage' => null,
                'description' => 'Spacious modular TV cabinet with hutch for display items.',
            ],
            
            // Coffee Tables
            [
                'name' => 'Round Coffee Table with Glass Top (Oak)',
                'price' => 12900,
                'original_price' => 25000,
                'category' => 'coffee-tables',
                'subcategory' => 'Round Coffee Tables',
                'image' => 'https://images.unsplash.com/photo-1586023492125-27b2c045efd7?w=800',
                'rating' => 4.4,
                'reviews' => 29,
                'in_stock' => true,
                'is_featured' => false,
                'hot_offer' => true,
                'offer_percentage' => 48,
                'description' => 'Elegant round coffee table with tempered glass top.',
            ],
            [
                'name' => 'Marble Top Coffee Table (Modern Design)',
                'price' => 18900,
                'original_price' => 38000,
                'category' => 'coffee-tables',
                'subcategory' => 'Marble Coffee Table',
                'image' => 'https://images.unsplash.com/photo-1586023492125-27b2c045efd7?w=800',
                'rating' => 4.7,
                'reviews' => 47,
                'in_stock' => true,
                'is_featured' => true,
                'hot_offer' => true,
                'offer_percentage' => 50,
                'description' => 'Luxury coffee table with premium marble top.',
            ],
            
            // Book Shelves
            [
                'name' => '5 Tier Wooden Bookshelf (Pine Wood)',
                'price' => 14900,
                'original_price' => 32000,
                'category' => 'book-shelves',
                'subcategory' => 'Bookshelves',
                'image' => 'https://images.unsplash.com/photo-1586023492125-27b2c045efd7?w=800',
                'rating' => 4.5,
                'reviews' => 34,
                'in_stock' => true,
                'is_featured' => false,
                'hot_offer' => true,
                'offer_percentage' => 53,
                'description' => 'Spacious 5-tier bookshelf for your home library.',
            ],
            [
                'name' => 'Wall Mounted Bookshelf (Floating Design)',
                'price' => 8900,
                'original_price' => 18000,
                'category' => 'book-shelves',
                'subcategory' => 'Wall Bookshelf',
                'image' => 'https://images.unsplash.com/photo-1586023492125-27b2c045efd7?w=800',
                'rating' => 4.3,
                'reviews' => 22,
                'in_stock' => true,
                'is_featured' => false,
                'hot_offer' => true,
                'offer_percentage' => 51,
                'description' => 'Modern floating wall-mounted bookshelf.',
            ],
            
            // Study Tables
            [
                'name' => 'Ergonomic Study Table with Drawers',
                'price' => 16900,
                'original_price' => 35000,
                'category' => 'study-tables',
                'subcategory' => 'Study Tables',
                'image' => 'https://images.unsplash.com/photo-1586023492125-27b2c045efd7?w=800',
                'rating' => 4.6,
                'reviews' => 39,
                'in_stock' => true,
                'is_featured' => true,
                'hot_offer' => true,
                'offer_percentage' => 52,
                'description' => 'Comfortable study table with storage drawers.',
            ],
            [
                'name' => 'Kids Study Table with Chair Set',
                'price' => 11900,
                'original_price' => 25000,
                'category' => 'study-tables',
                'subcategory' => 'Kids Study Tables',
                'image' => 'https://images.unsplash.com/photo-1586023492125-27b2c045efd7?w=800',
                'rating' => 4.4,
                'reviews' => 26,
                'in_stock' => true,
                'is_featured' => false,
                'hot_offer' => true,
                'offer_percentage' => 52,
                'description' => 'Colorful study table set designed for children.',
            ],

            // Office (slug: office)
            [
                'name' => 'Shreejee Blessings Wood Executive L-Shaped Office Desk (Walnut)',
                'price' => 42900,
                'original_price' => 72000,
                'category' => 'office',
                'subcategory' => 'Executive Desks',
                'image' => 'https://images.unsplash.com/photo-1497366216548-37526070297c?w=800',
                'rating' => 4.7,
                'reviews' => 31,
                'in_stock' => true,
                'is_featured' => true,
                'hot_offer' => true,
                'offer_percentage' => 40,
                'description' => 'Spacious L-shaped workstation with cable management and storage — ideal for cabins and home offices.',
            ],
            [
                'name' => 'Ergonomic Mesh Office Chair with Lumbar Support',
                'price' => 12900,
                'original_price' => 22000,
                'category' => 'office',
                'subcategory' => 'Office Chairs',
                'image' => 'https://images.unsplash.com/photo-1580480055273-228ff5388e8f?w=800',
                'rating' => 4.6,
                'reviews' => 54,
                'in_stock' => true,
                'is_featured' => true,
                'hot_offer' => false,
                'offer_percentage' => null,
                'description' => 'Breathable mesh back, adjustable height and tilt for long work sessions.',
            ],
            [
                'name' => '8-Seater Conference Table (Oak Finish)',
                'price' => 68900,
                'original_price' => 115000,
                'category' => 'office',
                'subcategory' => 'Conference Tables',
                'image' => 'https://images.unsplash.com/photo-1560250097-0b93528c311a?w=800',
                'rating' => 4.8,
                'reviews' => 19,
                'in_stock' => true,
                'is_featured' => false,
                'hot_offer' => true,
                'offer_percentage' => 40,
                'description' => 'Large meeting table with wire box — perfect for boardrooms.',
            ],

            // Outdoor (slug: outdoor)
            [
                'name' => 'Weather-Resistant 5-Seater Outdoor Sofa Set (Grey Wicker)',
                'price' => 55900,
                'original_price' => 92000,
                'category' => 'outdoor',
                'subcategory' => 'Patio Sofas',
                'image' => 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=800',
                'rating' => 4.7,
                'reviews' => 42,
                'in_stock' => true,
                'is_featured' => true,
                'hot_offer' => true,
                'offer_percentage' => 39,
                'description' => 'UV-resistant wicker with quick-dry cushions for balconies and gardens.',
            ],
            [
                'name' => 'Teak Wood Outdoor Dining Set (6-Seater)',
                'price' => 48900,
                'original_price' => 78000,
                'category' => 'outdoor',
                'subcategory' => 'Garden Dining',
                'image' => 'https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?w=800',
                'rating' => 4.6,
                'reviews' => 28,
                'in_stock' => true,
                'is_featured' => true,
                'hot_offer' => false,
                'offer_percentage' => null,
                'description' => 'Solid teak table and chairs, treated for outdoor use.',
            ],
            [
                'name' => 'Adjustable Sun Lounger with Side Table',
                'price' => 18900,
                'original_price' => 32000,
                'category' => 'outdoor',
                'subcategory' => 'Loungers',
                'image' => 'https://images.unsplash.com/photo-1600210492486-724fe5c67fb0?w=800',
                'rating' => 4.5,
                'reviews' => 36,
                'in_stock' => true,
                'is_featured' => false,
                'hot_offer' => true,
                'offer_percentage' => 41,
                'description' => 'Recline in style by the pool or terrace.',
            ],

            // Restaurant & hotel (slug: restaurant-hotel)
            [
                'name' => 'Upholstered Restaurant Dining Chair (Commercial Grade)',
                'price' => 4200,
                'original_price' => 7500,
                'category' => 'restaurant-hotel',
                'subcategory' => 'Dining Chairs',
                'image' => 'https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?w=800',
                'rating' => 4.5,
                'reviews' => 67,
                'in_stock' => true,
                'is_featured' => true,
                'hot_offer' => true,
                'offer_percentage' => 44,
                'description' => 'Stackable, easy-clean fabric — built for high-traffic cafés and restaurants.',
            ],
            [
                'name' => 'Hotel Lobby 3-Seater Sofa (Velvet)',
                'price' => 38500,
                'original_price' => 62000,
                'category' => 'restaurant-hotel',
                'subcategory' => 'Lobby Seating',
                'image' => 'https://images.unsplash.com/photo-1618221195710-dd6b41faaea6?w=800',
                'rating' => 4.7,
                'reviews' => 22,
                'in_stock' => true,
                'is_featured' => true,
                'hot_offer' => false,
                'offer_percentage' => null,
                'description' => 'Elegant reception seating with durable commercial frame.',
            ],
            [
                'name' => 'Solid Wood Restaurant Table (4-Seater)',
                'price' => 22500,
                'original_price' => 38000,
                'category' => 'restaurant-hotel',
                'subcategory' => 'Restaurant Tables',
                'image' => 'https://images.unsplash.com/photo-1550966871-3ed3cdb5ed0c?w=800',
                'rating' => 4.6,
                'reviews' => 41,
                'in_stock' => true,
                'is_featured' => false,
                'hot_offer' => true,
                'offer_percentage' => 41,
                'description' => 'Heavy-duty top for daily dining service.',
            ],

            // Banquet (slug: banquet)
            [
                'name' => 'Folding Banquet Table (6ft x 2.5ft)',
                'price' => 8900,
                'original_price' => 15000,
                'category' => 'banquet',
                'subcategory' => 'Folding Tables',
                'image' => 'https://images.unsplash.com/photo-1464366400600-7161149a31f0?w=800',
                'rating' => 4.4,
                'reviews' => 58,
                'in_stock' => true,
                'is_featured' => true,
                'hot_offer' => true,
                'offer_percentage' => 41,
                'description' => 'Lightweight, easy to store — weddings, halls, and events.',
            ],
            [
                'name' => 'Stackable Banquet Chair with Cushion (Gold Frame)',
                'price' => 2900,
                'original_price' => 4800,
                'category' => 'banquet',
                'subcategory' => 'Banquet Chairs',
                'image' => 'https://images.unsplash.com/photo-1519167758481-83f29da3a0a6?w=800',
                'rating' => 4.3,
                'reviews' => 72,
                'in_stock' => true,
                'is_featured' => true,
                'hot_offer' => false,
                'offer_percentage' => null,
                'description' => 'Elegant finish for receptions and community halls.',
            ],
            [
                'name' => 'Round Banquet Table (8-Seater, White Top)',
                'price' => 24900,
                'original_price' => 41000,
                'category' => 'banquet',
                'subcategory' => 'Round Tables',
                'image' => 'https://images.unsplash.com/photo-1530103862676-de8c9debad1d?w=800',
                'rating' => 4.6,
                'reviews' => 25,
                'in_stock' => true,
                'is_featured' => false,
                'hot_offer' => true,
                'offer_percentage' => 39,
                'description' => 'Spacious round layout for formal dinners.',
            ],

            // School (slug: school)
            [
                'name' => 'Student Desk & Chair Combo (Primary)',
                'price' => 4500,
                'original_price' => 7800,
                'category' => 'school',
                'subcategory' => 'Classroom Desks',
                'image' => 'https://images.unsplash.com/photo-1580582932707-520cae937bbd?w=800',
                'rating' => 4.5,
                'reviews' => 48,
                'in_stock' => true,
                'is_featured' => true,
                'hot_offer' => true,
                'offer_percentage' => 42,
                'description' => 'Durable laminate top with height-adjustable chair.',
            ],
            [
                'name' => 'Library Reading Table with Bench Seating',
                'price' => 28900,
                'original_price' => 45000,
                'category' => 'school',
                'subcategory' => 'Library Furniture',
                'image' => 'https://images.unsplash.com/photo-1521587760476-6c12a4b04090?w=800',
                'rating' => 4.6,
                'reviews' => 17,
                'in_stock' => true,
                'is_featured' => true,
                'hot_offer' => false,
                'offer_percentage' => null,
                'description' => 'Quiet study zones for schools and colleges.',
            ],
            [
                'name' => 'Science Lab Stool (Adjustable Height)',
                'price' => 2200,
                'original_price' => 3800,
                'category' => 'school',
                'subcategory' => 'Lab Furniture',
                'image' => 'https://images.unsplash.com/photo-1532094349884-543bc11b234d?w=800',
                'rating' => 4.4,
                'reviews' => 33,
                'in_stock' => true,
                'is_featured' => false,
                'hot_offer' => true,
                'offer_percentage' => 42,
                'description' => 'Anti-slip base, chemical-resistant seat.',
            ],

            // Hospital (slug: hospital)
            [
                'name' => 'Hospital Attendant Bed with Side Rails',
                'price' => 18500,
                'original_price' => 29000,
                'category' => 'hospital',
                'subcategory' => 'Patient Beds',
                'image' => 'https://images.unsplash.com/photo-1519494026892-80bbd2d6fd0d?w=800',
                'rating' => 4.5,
                'reviews' => 29,
                'in_stock' => true,
                'is_featured' => true,
                'hot_offer' => true,
                'offer_percentage' => 36,
                'description' => 'Easy-clean surfaces; suitable for clinics and care centres.',
            ],
            [
                'name' => 'Waiting Room 4-Seater Bench (PU Seat)',
                'price' => 15900,
                'original_price' => 26000,
                'category' => 'hospital',
                'subcategory' => 'Waiting Area',
                'image' => 'https://images.unsplash.com/photo-1629909613654-28e377c37b09?w=800',
                'rating' => 4.4,
                'reviews' => 21,
                'in_stock' => true,
                'is_featured' => true,
                'hot_offer' => false,
                'offer_percentage' => null,
                'description' => 'Wipeable upholstery for high-traffic reception areas.',
            ],
            [
                'name' => 'Medical Storage Cabinet (Lockable)',
                'price' => 12400,
                'original_price' => 20000,
                'category' => 'hospital',
                'subcategory' => 'Storage',
                'image' => 'https://images.unsplash.com/photo-1576091160399-112ba8d25d1d?w=800',
                'rating' => 4.6,
                'reviews' => 14,
                'in_stock' => true,
                'is_featured' => false,
                'hot_offer' => true,
                'offer_percentage' => 38,
                'description' => 'Steel body with adjustable shelves.',
            ],

            // Custom & bespoke (slug: customize)
            [
                'name' => 'Bespoke Wardrobe — Design Consultation & Build',
                'price' => 4999,
                'original_price' => null,
                'category' => 'customize',
                'subcategory' => 'Wardrobes',
                'image' => 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=800',
                'rating' => 4.9,
                'reviews' => 112,
                'in_stock' => true,
                'is_featured' => true,
                'hot_offer' => false,
                'offer_percentage' => null,
                'description' => 'Site visit, 3D layout, and manufacture to your exact dimensions. Final price quoted after design.',
            ],
            [
                'name' => 'Made-to-Order Solid Wood Dining Table',
                'price' => 8999,
                'original_price' => null,
                'category' => 'customize',
                'subcategory' => 'Dining Custom',
                'image' => 'https://images.unsplash.com/photo-1617806118233-18e1de247200?w=800',
                'rating' => 4.8,
                'reviews' => 86,
                'in_stock' => true,
                'is_featured' => true,
                'hot_offer' => false,
                'offer_percentage' => null,
                'description' => 'Choose wood, finish, length, and seating capacity. Crafted at our Delhi NCR workshop.',
            ],
            [
                'name' => 'Custom TV Unit & Wall Panel System',
                'price' => 6499,
                'original_price' => null,
                'category' => 'customize',
                'subcategory' => 'Living Custom',
                'image' => 'https://images.unsplash.com/photo-1598928506311-c55ded91a20c?w=800',
                'rating' => 4.7,
                'reviews' => 64,
                'in_stock' => true,
                'is_featured' => false,
                'hot_offer' => false,
                'offer_percentage' => null,
                'description' => 'Modular or full-wall designs with cable management and lighting options.',
            ],
        ];

        foreach ($products as $productData) {
            $category = $categories->firstWhere('slug', $productData['category']);
            if (!$category) continue;

            Product::firstOrCreate(
                ['name' => $productData['name']],
                [
                    'price' => $productData['price'],
                    'original_price' => $productData['original_price'],
                    'category_id' => $category->id,
                    'subcategory' => $productData['subcategory'],
                    'image' => $productData['image'],
                    'rating' => $productData['rating'],
                    'reviews' => $productData['reviews'],
                    'in_stock' => $productData['in_stock'],
                    'is_featured' => $productData['is_featured'],
                    'hot_offer' => $productData['hot_offer'],
                    'offer_percentage' => $productData['offer_percentage'],
                    'description' => $productData['description'],
                ]
            );
        }
    }
}

