<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Product;
use App\Models\Category;

class ProductSeeder extends Seeder
{
    public function run(): void
    {
        $categories = Category::all();
        
        // Product data with images
        $products = [
            // Beds
            [
                'name' => 'Wood State Daffodil King Bed with Box Storage (Walnut)',
                'price' => 21990,
                'original_price' => 69000,
                'category' => 'beds',
                'subcategory' => 'King Size Beds',
                'image' => 'https://images.unsplash.com/photo-1631049307264-da0ec9d70304?w=800',
                'rating' => 4.5,
                'reviews' => 24,
                'in_stock' => true,
                'is_featured' => true,
                'hot_offer' => true,
                'offer_percentage' => 68,
                'description' => 'Premium king size bed with spacious box storage. Made from high-quality walnut wood with elegant design.',
            ],
            [
                'name' => 'Wood State King Bed without Storage (Walnut)',
                'price' => 15500,
                'original_price' => 50000,
                'category' => 'beds',
                'subcategory' => 'King Size Beds',
                'image' => 'https://images.unsplash.com/photo-1586023492125-27b2c045efd7?w=800',
                'rating' => 4.3,
                'reviews' => 18,
                'in_stock' => true,
                'is_featured' => true,
                'hot_offer' => true,
                'offer_percentage' => 69,
                'description' => 'Elegant king size bed without storage. Perfect for modern bedrooms.',
            ],
            [
                'name' => 'Wood State Queen Bed with Storage (Oak)',
                'price' => 18990,
                'original_price' => 45000,
                'category' => 'beds',
                'subcategory' => 'Queen Size Beds',
                'image' => 'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=800',
                'rating' => 4.6,
                'reviews' => 32,
                'in_stock' => true,
                'is_featured' => false,
                'hot_offer' => true,
                'offer_percentage' => 58,
                'description' => 'Spacious queen bed with under-bed storage compartments.',
            ],
            [
                'name' => 'Modern Platform Bed (Teak Wood)',
                'price' => 24990,
                'original_price' => 55000,
                'category' => 'beds',
                'subcategory' => 'Platform Beds',
                'image' => 'https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?w=800',
                'rating' => 4.7,
                'reviews' => 45,
                'in_stock' => true,
                'is_featured' => true,
                'hot_offer' => false,
                'offer_percentage' => null,
                'description' => 'Contemporary platform bed in premium teak wood finish.',
            ],
            [
                'name' => 'Hydraulic Storage Bed (Mahogany)',
                'price' => 32990,
                'original_price' => 75000,
                'category' => 'beds',
                'subcategory' => 'Hydraulic Beds',
                'image' => 'https://images.unsplash.com/photo-1631889993954-1b3b9b4b5e5e?w=800',
                'rating' => 4.8,
                'reviews' => 56,
                'in_stock' => true,
                'is_featured' => true,
                'hot_offer' => true,
                'offer_percentage' => 56,
                'description' => 'Luxury hydraulic bed with easy-lift storage mechanism.',
            ],
            [
                'name' => 'Classic Wooden Bed with Headboard (Sheesham)',
                'price' => 17990,
                'original_price' => 42000,
                'category' => 'beds',
                'subcategory' => 'Queen Size Beds',
                'image' => 'https://images.unsplash.com/photo-1631049307264-da0ec9d70304?w=800',
                'rating' => 4.4,
                'reviews' => 28,
                'in_stock' => true,
                'is_featured' => false,
                'hot_offer' => true,
                'offer_percentage' => 57,
                'description' => 'Beautiful classic wooden bed with elegant headboard in premium sheesham wood.',
            ],
            
            // Sofa Sets
            [
                'name' => 'Duroflex Ease 3 Seater Fabric Sofa In Beige Colour',
                'price' => 19152,
                'original_price' => 33600,
                'category' => 'sofa-sets',
                'subcategory' => '3-Seaters Sofas',
                'image' => 'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=800',
                'rating' => 4.4,
                'reviews' => 28,
                'in_stock' => true,
                'is_featured' => true,
                'hot_offer' => true,
                'offer_percentage' => 43,
                'description' => 'Comfortable 3-seater fabric sofa in elegant beige color.',
            ],
            [
                'name' => 'Home Lifestylez Belfast 3 Seater Velvet Sofa In Grey Color',
                'price' => 40500,
                'original_price' => 55500,
                'category' => 'sofa-sets',
                'subcategory' => '3-Seaters Sofas',
                'image' => 'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=800',
                'rating' => 4.6,
                'reviews' => 41,
                'in_stock' => true,
                'is_featured' => true,
                'hot_offer' => false,
                'offer_percentage' => null,
                'description' => 'Luxurious velvet sofa in modern grey shade.',
            ],
            [
                'name' => 'Caraven 2 Seater Velvet Sofa In Navy Blue Color',
                'price' => 27500,
                'original_price' => 40500,
                'category' => 'sofa-sets',
                'subcategory' => '2-Seater Sofas',
                'image' => 'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=800',
                'rating' => 4.5,
                'reviews' => 35,
                'in_stock' => true,
                'is_featured' => false,
                'hot_offer' => true,
                'offer_percentage' => 32,
                'description' => 'Compact 2-seater velvet sofa perfect for small spaces.',
            ],
            [
                'name' => 'Duroflex Utopia 1 Seater Fabric Sofa In Grey Colour',
                'price' => 12500,
                'original_price' => 22000,
                'category' => 'sofa-sets',
                'subcategory' => '1-Seater Sofas',
                'image' => 'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=800',
                'rating' => 4.2,
                'reviews' => 19,
                'in_stock' => true,
                'is_featured' => false,
                'hot_offer' => true,
                'offer_percentage' => 43,
                'description' => 'Stylish single seater fabric sofa in grey.',
            ],
            [
                'name' => 'Premium Leather 3 Seater Sofa Set',
                'price' => 89900,
                'original_price' => 150000,
                'category' => 'sofa-sets',
                'subcategory' => '3-Seaters Sofas',
                'image' => 'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=800',
                'rating' => 4.9,
                'reviews' => 67,
                'in_stock' => true,
                'is_featured' => true,
                'hot_offer' => true,
                'offer_percentage' => 40,
                'description' => 'Luxury genuine leather 3-seater sofa set with premium finish.',
            ],
            [
                'name' => 'Modern L-Shaped Corner Sofa Set (Grey Fabric)',
                'price' => 45900,
                'original_price' => 85000,
                'category' => 'sofa-sets',
                'subcategory' => 'L-Shaped Sofas',
                'image' => 'https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=800',
                'rating' => 4.6,
                'reviews' => 42,
                'in_stock' => true,
                'is_featured' => true,
                'hot_offer' => true,
                'offer_percentage' => 46,
                'description' => 'Spacious L-shaped corner sofa perfect for modern living rooms. Comfortable and stylish.',
            ],
            
            // Dining Tables
            [
                'name' => 'Modern 6 Seater Dining Table Set (Oak Wood)',
                'price' => 45900,
                'original_price' => 85000,
                'category' => 'dining-table-sets',
                'subcategory' => '6-Seater Dining Table',
                'image' => 'https://images.unsplash.com/photo-1586023492125-27b2c045efd7?w=800',
                'rating' => 4.7,
                'reviews' => 52,
                'in_stock' => true,
                'is_featured' => true,
                'hot_offer' => true,
                'offer_percentage' => 46,
                'description' => 'Elegant 6-seater dining table with matching chairs in oak finish.',
            ],
            [
                'name' => 'Classic 4 Seater Dining Table (Teak)',
                'price' => 32900,
                'original_price' => 65000,
                'category' => 'dining-table-sets',
                'subcategory' => '4-Seater Dining Table',
                'image' => 'https://images.unsplash.com/photo-1586023492125-27b2c045efd7?w=800',
                'rating' => 4.5,
                'reviews' => 38,
                'in_stock' => true,
                'is_featured' => false,
                'hot_offer' => true,
                'offer_percentage' => 49,
                'description' => 'Beautiful 4-seater dining table in premium teak wood.',
            ],
            
            // TV Units
            [
                'name' => 'Wall Mount TV Unit with Storage (Walnut)',
                'price' => 28900,
                'original_price' => 55000,
                'category' => 'tv-units',
                'subcategory' => 'Wall Mount Tv Units',
                'image' => 'https://images.unsplash.com/photo-1586023492125-27b2c045efd7?w=800',
                'rating' => 4.6,
                'reviews' => 43,
                'in_stock' => true,
                'is_featured' => true,
                'hot_offer' => true,
                'offer_percentage' => 47,
                'description' => 'Modern wall-mounted TV unit with ample storage space.',
            ],
            [
                'name' => 'Modular TV Cabinet with Hutch',
                'price' => 35900,
                'original_price' => 70000,
                'category' => 'tv-units',
                'subcategory' => 'Hutch Tv Units',
                'image' => 'https://images.unsplash.com/photo-1586023492125-27b2c045efd7?w=800',
                'rating' => 4.8,
                'reviews' => 61,
                'in_stock' => true,
                'is_featured' => true,
                'hot_offer' => false,
                'offer_percentage' => null,
                'description' => 'Spacious modular TV cabinet with hutch for display items.',
            ],
            
            // Coffee Tables
            [
                'name' => 'Round Coffee Table with Glass Top (Oak)',
                'price' => 12900,
                'original_price' => 25000,
                'category' => 'coffee-tables',
                'subcategory' => 'Round Coffee Tables',
                'image' => 'https://images.unsplash.com/photo-1586023492125-27b2c045efd7?w=800',
                'rating' => 4.4,
                'reviews' => 29,
                'in_stock' => true,
                'is_featured' => false,
                'hot_offer' => true,
                'offer_percentage' => 48,
                'description' => 'Elegant round coffee table with tempered glass top.',
            ],
            [
                'name' => 'Marble Top Coffee Table (Modern Design)',
                'price' => 18900,
                'original_price' => 38000,
                'category' => 'coffee-tables',
                'subcategory' => 'Marble Coffee Table',
                'image' => 'https://images.unsplash.com/photo-1586023492125-27b2c045efd7?w=800',
                'rating' => 4.7,
                'reviews' => 47,
                'in_stock' => true,
                'is_featured' => true,
                'hot_offer' => true,
                'offer_percentage' => 50,
                'description' => 'Luxury coffee table with premium marble top.',
            ],
            
            // Book Shelves
            [
                'name' => '5 Tier Wooden Bookshelf (Pine Wood)',
                'price' => 14900,
                'original_price' => 32000,
                'category' => 'book-shelves',
                'subcategory' => 'Bookshelves',
                'image' => 'https://images.unsplash.com/photo-1586023492125-27b2c045efd7?w=800',
                'rating' => 4.5,
                'reviews' => 34,
                'in_stock' => true,
                'is_featured' => false,
                'hot_offer' => true,
                'offer_percentage' => 53,
                'description' => 'Spacious 5-tier bookshelf for your home library.',
            ],
            [
                'name' => 'Wall Mounted Bookshelf (Floating Design)',
                'price' => 8900,
                'original_price' => 18000,
                'category' => 'book-shelves',
                'subcategory' => 'Wall Bookshelf',
                'image' => 'https://images.unsplash.com/photo-1586023492125-27b2c045efd7?w=800',
                'rating' => 4.3,
                'reviews' => 22,
                'in_stock' => true,
                'is_featured' => false,
                'hot_offer' => true,
                'offer_percentage' => 51,
                'description' => 'Modern floating wall-mounted bookshelf.',
            ],
            
            // Study Tables
            [
                'name' => 'Ergonomic Study Table with Drawers',
                'price' => 16900,
                'original_price' => 35000,
                'category' => 'study-tables',
                'subcategory' => 'Study Tables',
                'image' => 'https://images.unsplash.com/photo-1586023492125-27b2c045efd7?w=800',
                'rating' => 4.6,
                'reviews' => 39,
                'in_stock' => true,
                'is_featured' => true,
                'hot_offer' => true,
                'offer_percentage' => 52,
                'description' => 'Comfortable study table with storage drawers.',
            ],
            [
                'name' => 'Kids Study Table with Chair Set',
                'price' => 11900,
                'original_price' => 25000,
                'category' => 'study-tables',
                'subcategory' => 'Kids Study Tables',
                'image' => 'https://images.unsplash.com/photo-1586023492125-27b2c045efd7?w=800',
                'rating' => 4.4,
                'reviews' => 26,
                'in_stock' => true,
                'is_featured' => false,
                'hot_offer' => true,
                'offer_percentage' => 52,
                'description' => 'Colorful study table set designed for children.',
            ],
        ];

        foreach ($products as $productData) {
            $category = $categories->firstWhere('slug', $productData['category']);
            if (!$category) continue;

            Product::firstOrCreate(
                ['name' => $productData['name']],
                [
                    'price' => $productData['price'],
                    'original_price' => $productData['original_price'],
                    'category_id' => $category->id,
                    'subcategory' => $productData['subcategory'],
                    'image' => $productData['image'],
                    'rating' => $productData['rating'],
                    'reviews' => $productData['reviews'],
                    'in_stock' => $productData['in_stock'],
                    'is_featured' => $productData['is_featured'],
                    'hot_offer' => $productData['hot_offer'],
                    'offer_percentage' => $productData['offer_percentage'],
                    'description' => $productData['description'],
                ]
            );
        }
    }
}

