<?php

namespace App\Console\Commands;

use Illuminate\Console\Command;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Schema;

/**
 * Exports application rows from Supabase (import_source) as MySQL INSERTs for phpMyAdmin on Hostinger.
 * Run migrations on Hostinger first, then import the generated file.
 */
class ExportMysqlDumpFromSupabase extends Command
{
    protected $signature = 'db:export-mysql-for-hostinger
                            {--path= : Output .sql path (default: database/exports/hostinger-data.sql)}';

    protected $description = 'Export Supabase data as MySQL INSERT statements for Hostinger phpMyAdmin import';

    /** @var list<string> */
    private const TABLES = [
        'categories',
        'products',
        'users',
        'orders',
        'order_items',
        'order_payments',
        'order_payment_screenshots',
    ];

    public function handle(): int
    {
        try {
            DB::connection('import_source')->getPdo();
        } catch (\Throwable $e) {
            $this->error('Cannot connect to import_source. Set IMPORT_SOURCE_DB_* in .env');
            $this->line($e->getMessage());

            return self::FAILURE;
        }

        $path = $this->option('path')
            ?: database_path('exports/hostinger-data.sql');

        $dir = dirname($path);
        if (! is_dir($dir)) {
            mkdir($dir, 0755, true);
        }

        $fh = fopen($path, 'w');
        if ($fh === false) {
            $this->error("Cannot write: {$path}");

            return self::FAILURE;
        }

        fwrite($fh, "-- Generated by php artisan db:export-mysql-for-hostinger\n");
        fwrite($fh, "-- Import on Hostinger AFTER: php artisan migrate --force\n");
        fwrite($fh, "SET NAMES utf8mb4;\nSET FOREIGN_KEY_CHECKS=0;\n\n");

        $total = 0;
        foreach (self::TABLES as $table) {
            if (! Schema::connection('import_source')->hasTable($table)) {
                $this->warn("Skip [{$table}] — not on source");

                continue;
            }

            $n = $this->exportTable($fh, $table);
            $total += $n;
            $this->info("Exported [{$table}]: {$n} rows");
        }

        fwrite($fh, "\nSET FOREIGN_KEY_CHECKS=1;\n");
        fclose($fh);

        $this->newLine();
        $this->info("Wrote {$total} rows to: {$path}");
        $this->line('Hostinger: phpMyAdmin → u274811071_shreejee → Import this file');

        return self::SUCCESS;
    }

    private function exportTable($fh, string $table): int
    {
        $query = DB::connection('import_source')->table($table);
        if (Schema::connection('import_source')->hasColumn($table, 'id')) {
            $query->orderBy('id');
        }

        $count = 0;
        $columns = null;

        foreach ($query->cursor() as $row) {
            $row = (array) $row;
            if ($columns === null) {
                $columns = array_keys($row);
                fwrite($fh, "\n-- {$table}\n");
            }

            $values = array_map(fn ($v) => $this->sqlValue($v), array_values($row));
            $colList = '`'.implode('`,`', $columns).'`';
            $line = 'INSERT INTO `'.$table.'` ('.$colList.') VALUES ('.implode(',', $values).');'."\n";
            fwrite($fh, $line);
            $count++;
        }

        return $count;
    }

    private function sqlValue(mixed $v): string
    {
        if ($v === null) {
            return 'NULL';
        }
        if (is_bool($v)) {
            return $v ? '1' : '0';
        }
        if (is_int($v) || is_float($v)) {
            return (string) $v;
        }
        if ($v instanceof \DateTimeInterface) {
            return "'".$v->format('Y-m-d H:i:s')."'";
        }

        return "'".str_replace(["\\", "'"], ["\\\\", "\\'"], (string) $v)."'";
    }
}
